[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Tom Scott <tomscott87@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"